gdocs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^oauth2callback/', views.auth_return, name='oauth2callback'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^new/', views.new_document, name='new'),
    url(r'^(?P<document_id>[0-9]+)/remove/$', views.remove_document, name='remove'),
    url(r'^(?P<document_id>[0-9]+)/edit/$', views.edit_document, name='edit'),
]

gdocs_test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^gdocs/', include('gdocs.urls', namespace='gdocs')),
    # url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'gdocs/login.html'}),
    url(r'^$', 'gdocs.views.index'),
]

gdocs/models.py
#-*- coding: utf8 -*-

from django.db import models
from django.contrib.auth.models import User

from oauth2client.django_orm import CredentialsField

class Document(models.Model):
    """Информация о документе"""
    updated_at = models.DateTimeField()
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=500)
    remote_id = models.CharField(max_length=200)
    users = models.ManyToManyField(User, through='Permissions')

    def __unicode__(self):
        return self.name

class Permissions(models.Model):
    """Информация о правах пользователя"""
    class Meta:
        unique_together = (('user', 'document'),)
    OWNER = 'owner'
    WRITER = 'writer'
    READER = 'reader'
    PERMISSIONS_SET = (
        # (OWNER, 'Owner'),
        (READER, 'Reader'),
        (WRITER, 'Writer'),
    )
    document = models.ForeignKey(Document)
    user = models.ForeignKey(User)
    remote_id = models.CharField(max_length=200)
    permission = models.CharField(max_length=6,
                                  choices=PERMISSIONS_SET,
                                  default=READER)

class CredentialsModel(models.Model):
    id = models.ForeignKey(User, primary_key=True)
    credential = CredentialsField()

gdocs/forms/document.py
#-*- coding: utf8 -*-

from django import forms

from ..models import Document, Permissions

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['name','id']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'id': forms.HiddenInput(),
        }
        exclude=['remote_id']

PermissionFormSet = forms.inlineformset_factory(Document, Permissions,
                            fields=['user', 'permission', 'id'],
                            widgets={'user': forms.widgets.Select(attrs={'class': 'form-control'}),
                                     'permission': forms.widgets.Select(attrs={'class': 'form-control'}),
                                     'id': forms.HiddenInput(),
                                     },
                            extra=5, max_num=5, exclude=['remote_id']
                            )

gdocs/forms/user.py
#-*- coding: utf8 -*-

from django import forms
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    """Форма создания пользователя с обязательным полем email"""
    class Meta:
        fields = ("username", "email",)
    email = forms.EmailField(required=True)

gdocs/views.py
#-*- coding: utf8 -*-

import httplib2
import os

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect

from oauth2client.django_orm import Storage
from oauth2client import client, xsrfutil

from apiclient import discovery
from gdocs.forms.document import PermissionFormSet

from gdocs_test1 import settings
from .models import Document, CredentialsModel
from .forms.document import DocumentForm
from bl.document import create_document, create_permissions, edit_document as bl_edit_document
from .utils import check_oauth, get_drive_service, get_credential, FLOW



@csrf_protect
@login_required()
def index(request):
    '''Отобразить все добавленные документы'''

    credential = get_credential(request.user)
    authorize_url = check_oauth(credential, request.user)
    if authorize_url: return HttpResponseRedirect(authorize_url)

    document_list = Document.objects.order_by('-updated_at')
    context = {'document_list': document_list}

    return render(request, 'gdocs/index.html', context)

@login_required
def new_document(request):
    """Добавление нового документа"""
    credential = get_credential(request.user)
    authorize_url = check_oauth(credential, request.user)
    if authorize_url: return HttpResponseRedirect(authorize_url)

    # Получение экземпляра Drive API service
    service = get_drive_service(credential)
    if request.method == 'POST':
        # Обработка введенных данных
        form = DocumentForm(request.POST)
        if form.is_valid():
            document = form.save(commit=False)
            formset = PermissionFormSet(request.POST, instance=document)
            if formset.is_valid():
                create_document(service, document)
                permissions = formset.save(commit=False)
                create_permissions(service, permissions)
                return HttpResponseRedirect('/')
        else:
            formset = PermissionFormSet(request.POST)
    else:
        # Создание пустой формы для ввода
        document = Document()
        form = DocumentForm(instance=document)
        formset = PermissionFormSet(instance=document)
    return render(request, 'gdocs/new.html', {'form': form, 'formset':formset}, context_instance=RequestContext(request))

@login_required
def edit_document(request, document_id):
    """Редактирование документа"""
    document = get_object_or_404(Document, pk=document_id)
    credential = get_credential(request.user)
    authorize_url = check_oauth(credential, request.user)
    if authorize_url:
        return HttpResponseRedirect(authorize_url)

    # Получение экземпляра Drive API service
    service = get_drive_service(credential)
    if request.method == 'POST':
        form = DocumentForm(request.POST, instance=document)
        formset = PermissionFormSet(request.POST, instance=document)
        if form.is_valid() and formset.is_valid():
            document = form.save(commit=False)
            permissions = formset.save(commit=False)
            bl_edit_document(service, document, permissions, formset.deleted_objects)
            return HttpResponseRedirect('/')
    else:
        form = DocumentForm(instance=document)
        formset = PermissionFormSet(instance=document)
    return render(request, 'gdocs/new.html', {'form': form, 'formset': formset}, context_instance=RequestContext(request))

@login_required
def remove_document(request, document_id):
    """Удаление документа.

    Удаление производится локально и не затрагивает данные в Google Drive."""
    document = get_object_or_404(Document, pk=document_id)
    document.delete()
    return HttpResponseRedirect('/')


# Authentication views
@csrf_protect
@login_required
def auth_return(request):
    # TODO: применяется ли csrf-protection из Django в данном случае, или лучше чинить validate_token?
    # if not xsrfutil.validate_token(settings.SECRET_KEY, request.REQUEST['state'],
    #                                 request.user):
    #     return  HttpResponseBadRequest()
    credential = FLOW.step2_exchange(request.REQUEST)
    storage = Storage(CredentialsModel, 'id', request.user, 'credential')
    storage.put(credential)
    return HttpResponseRedirect("/")

def login(request):
    return render(request, 'gdocs/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")

gdocs/templates/gdocs/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>gDocs viewer.</title>

    {% load staticfiles %}
    <!-- Bootstrap -->
    <link href="{% static "gdocs/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "gdocs/css/styles.css" %}" rel="stylesheet">
</head>
<body>

{% block page %}
    {% block content %}
    {% endblock %}
{% endblock %}
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="{% static "gdocs/js/script.js" %}" type="text/javascript"></script>
</body>
</html>

gdocs/templates/gdocs/index.html
{% extends "gdocs/base.html" %}
{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
            {% if document_list %}
                <table class='table'>
                    <tr>
                        <th>#</th>
                        <th></th>
                        <th></th>
                        <th>Name</th>
                        <th></th>
                        <th>Url</th>
                    </tr>
                {% for document in document_list %}
                    <tr>
                        <td width="2%">{{ forloop.counter }} </td>
                        <td width="2%">
                            <a href="{% url 'gdocs:remove' document.id%}" title="Remove">
                              <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                            </a>
                        </td>
                        <td width="2%">
                            {% if user in document.users.select_related  %}
                            <a href="{% url 'gdocs:edit' document.id %}" title="Edit">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>
                            {% endif %}
                        </td>
                        <td width="20%">{{ document.name }}</td>
                        <td width="5%">{% if user in document.users.select_related  %} <small class="small"><em>accessible</em></small>{% endif %}</td>
                        <td width="70%"><a href="{{ document.url }}">{{ document.url }}</a></td>
                    </tr>
                {% endfor %}
                </table>
            {% else %}
                <h2>No documents available yet.</h2>
            {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-md-offset-1">
                <a class="btn btn-default" href="{% url 'gdocs:new' %}" role="button">Add</a>
            </div>
            <div class="col-md-1 col-md-offset-6">
                <a class="btn btn-default" href="{% url 'gdocs:logout' %}" role="button">Logout</a>
            </div>
        </div>
    </div>
{% endblock %}

gdocs/templates/gdocs/login.html
{% extends "gdocs/base.html" %}
{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-md-offset-3">
            <h2>Sign in</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-3">
            {% if form.errors %}
            <p>Неверное имя пользователя или пароль. Пожалуйста, попробуйте еще раз.</p>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-3">
            <form method="post" class="form-horizontal" action="{% url 'django.contrib.auth.views.login' %}">
                {% csrf_token %}
                <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                </table>

                <input type="submit" class="btn btn-default" value="login" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

gdocs/templates/gdocs/new.html
{% extends "gdocs/base.html" %}
{% block content %}
<form class="form-horizontal" action="{{ request.path }}" method="post">
    {% csrf_token %}
    <div class="row"><div class="col-md-7 col-md-offset-3"><h2>Введите информацию о документе</h2></div></div>
    {% if formset.non_form_errors %}
    <div class="form-group has-error">
        <div class="col-md-7 col-md-offset-3 control-label field-error">
            {{ formset.non_form_errors }}
        </div>
    </div>
    {% endif %}
    {% if form.name.errors %}
    <div class="form-group has-error">
        <div class="col-md-2 col-md-offset-3 control-label field-error">
            {{ form.name.errors.as_text }}
        </div>
    </div>
    {% endif %}
    <div class="form-group">
        <label for="name" class="col-md-1 col-md-offset-2 control-label">{{ form.name.label }}</label>
        <div class="col-md-7">
            {{ form.name }}
        </div>
    </div>
    {{ form.id }}
    {{ form.DELETE }}

    {{formset.management_form}}
    {% for permission_form in formset %}
    <div class="form-group" id="user{{forloop.counter}}">
        <label for="user1" class="col-md-1 col-md-offset-2 control-label">{{ permission_form.user.label }}</label>
        <div class="col-md-4">
            {{ permission_form.user }}
        </div>
        <label for="permission1" class="col-md-1 control-label"> {{ permission_form.permission.label}}</label>
        <div class="col-md-2">
            {{ permission_form.permission }}
        </div>
        {{ permission_form.id }}
        <div class="delete"> {{ permission_form.DELETE }} </div>
    </div>
    {% endfor %}


    <div class="col-md-1 col-md-offset-9 submit-button">
        <input class="btn btn-default" type="submit" value="Submit" />
    </div>
</form>


{% endblock %}